# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.synced_folder "./provisioning", "/vagrant_data"

  config.vm.define "vagrant4" do |vagrant4|
    vagrant4.vm.box = "ubuntu/trusty64"
    vagrant4.vm.network :private_network, ip: "192.168.55.55"
    vagrant4.vm.network "forwarded_port", guest: 3000, host: 3000
    vagrant4.vm.network "forwarded_port", guest: 443, host: 8443
  end

end
